In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.4.1


In [4]:
a = tf.constant([[1,2],[3,4]])

In [5]:
a.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [6]:
type(a.numpy())

numpy.ndarray

In [7]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [8]:
tf.zeros((2,2), dtype = tf.float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [9]:
tf.ones((2,2), dtype = tf.float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [10]:
tf.fill((2,3),9)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)>

In [13]:
y = tf.constant([[2,3],[3,4]])
tf.random.shuffle(y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [2, 3]], dtype=int32)>

In [14]:
5 / 0.19

26.31578947368421