In [1]:
import numpy as np
import pandas as pd

In [22]:
p11 = 0.8
p21 = 0.5
p31 = 0.6
v12=300
v22 = 1000
v32 = 600

#########
p211 = 0.2
p221 = 0.5
p231 = 0.4
v212 = -150
v222 = -400
v232 = -50

In [23]:
p11*v12+p211*v212

210.0

In [24]:
p21*v22+p221*v222

300.0

In [25]:
p31*v32 + p231*v232

340.0

In [27]:
mtr= np.matrix([[p11*v12, p211*v212],[p21*v22, p221*v222],[p31*v32,p231*v232]])

In [31]:
max_num1 = mtr[]

In [34]:
max_num2 = mtr.min()

In [35]:
max_num, min_num

(500.0, -200.0)

In [28]:
mtr

matrix([[ 240.,  -30.],
        [ 500., -200.],
        [ 360.,  -20.]])

In [2]:
e11 = -0.78
e12 = -0.62

In [68]:
a = np.matrix([[5.4,4.4],[-2.6,-1.6],[-3.6,-2.6],[2.4,1.9],[-1.6,-2.1]])
a.shape

(5, 2)

In [69]:
e = np.matrix([e11,e12]).T
e.shape

(2, 1)

In [73]:
a

matrix([[ 5.4,  4.4],
        [-2.6, -1.6],
        [-3.6, -2.6],
        [ 2.4,  1.9],
        [-1.6, -2.1]])

In [74]:
e

matrix([[-0.78],
        [-0.62]])

In [71]:
result = a.dot(e)

In [72]:
np.var(result)

18.525080000000003

# b minimax
alternative c
# c maximax  
alternative b 
# d minimum-regret-reget
alternative 
# e Hurwicz-Prinzip(70%)