In [1]:
import numpy as np 
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [2]:
df.drop('species', axis=1, inplace = True)

In [3]:
from sklearn.preprocessing import StandardScaler

In [4]:
transformer = StandardScaler()
transformer.fit(df)
df_scale=transformer.transform(df)
df_scale[:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [5]:
features = df_scale.T 
cov_matrix = np.cov(features) # cal covarr matrix
cov_matrix[:5]

array([[ 1.00671141, -0.11010327,  0.87760486,  0.82344326],
       [-0.11010327,  1.00671141, -0.42333835, -0.358937  ],
       [ 0.87760486, -0.42333835,  1.00671141,  0.96921855],
       [ 0.82344326, -0.358937  ,  0.96921855,  1.00671141]])

# ????? got lost from here

In [6]:
values, vectors = np.linalg.eig(cov_matrix) #the first element represents eigenvalues and the second one represents eigenvectors
values[:5],vectors[:5]

(array([2.93035378, 0.92740362, 0.14834223, 0.02074601]),
 array([[ 0.52237162, -0.37231836, -0.72101681,  0.26199559],
        [-0.26335492, -0.92555649,  0.24203288, -0.12413481],
        [ 0.58125401, -0.02109478,  0.14089226, -0.80115427],
        [ 0.56561105, -0.06541577,  0.6338014 ,  0.52354627]]))

In [7]:
# calculate the percentage of explained variance per principal component
explained_value=[]
for i in range(len(values)):
    explained_value.append(values[i]/ np.sum(values))
print (np.sum(explained_value), '\n',explained_value)

1.0 
 [0.7277045209380134, 0.2303052326768065, 0.03683831957627377, 0.005151926808906323]


# ?????what is the meaning of dot
projected_1 = df_scale.dot(vectors.T[0])
projected_2 = df_scale.dot(vectors.T[1])

In [34]:
res = pd.DataFrame(projected_1, columns=['PC1'])
res['PC2'] = projected_2
#res['Y'] = y
res.head()

PC1       PC2
0 -2.264542 -0.505704
1 -2.086426  0.655405
2 -2.367950  0.318477
3 -2.304197  0.575368
4 -2.388777 -0.674767