In [1]:
import numpy as np
import math

Difference on **np.array()** and **np.matrix()**

Results on **np.dot()** **np.multiply()** and *

In [27]:
'''build (3,1) array'''
a = np.array([1,-1,1])
a = a.reshape(-1,1) # !!! very import to reshape the array.
a.shape

(3, 1)

In [28]:
'''build (3,1) matrix'''
a_ = np.matrix([1,-1,1]).T
a_.shape

(3, 1)

In [30]:
a.dot(a.T) # needs to follow the matrix multiplication rules

array([[ 1, -1,  1],
       [-1,  1, -1],
       [ 1, -1,  1]])

In [31]:
a*a #do not need to follow the matrix multiplication rules

array([[1],
       [1],
       [1]])

In [23]:
np.multiply(a,a) #do not need to follow the matrix multiplication rules

array([[1],
       [1],
       [1]])

In [24]:
a_.dot(a_.T) #need to follow the matrix multiplication rules

matrix([[ 1, -1,  1],
        [-1,  1, -1],
        [ 1, -1,  1]])

In [25]:
a_*a_.T #need to follow the matrix multiplication rules

matrix([[ 1, -1,  1],
        [-1,  1, -1],
        [ 1, -1,  1]])

In [26]:
np.multiply(a_,a_) #do not need to follow the matrix multiplication rules

matrix([[1],
        [1],
        [1]])

# Matrix Multiplication

if 
$$ \boldsymbol{x}=\begin{pmatrix}x_1&x_2&\cdots&x_m\end{pmatrix},\quad A=\begin{pmatrix}a_{11}&a_{12}&\cdots&a_{1n}\\
               a_{21}&a_{22}&\cdots&a_{2n}\\
               \vdots&\quad&\quad&\vdots\\
               a_{m1}&a_{m2}&\cdots&a_{mn} 
\end{pmatrix} $$

A left multiply X

$$ \boldsymbol{x}A=\begin{pmatrix}\color{blue}{x_1}&\color{blue}{x_2}&\cdots&\color{blue}{x_m}\end{pmatrix}
\begin{pmatrix}a_{11}&a_{12}&\cdots&a_{1n}\\
               a_{21}&a_{22}&\cdots&a_{2n}\\
               \vdots&\quad&\quad&\vdots\\
               a_{m1}&a_{m2}&\cdots&a_{mn}
    \end{pmatrix}=
\color{blue}{x_1}\begin{pmatrix}a_{11}&a_{12}&\cdots&a_{1n}\end{pmatrix}+
\color{blue}{x_2}\begin{pmatrix}a_{21}&a_{22}&\cdots&a_{2n}\end{pmatrix}+\cdots+\color{blue}{x_m}\begin{pmatrix}a_{m1}&a_{m2}&\cdots&a_{mn}\end{pmatrix} $$


A right multiply X

$$ 
A\boldsymbol{x}=\begin{pmatrix}a_{11}&a_{12}&\cdots&a_{1n}\\
               a_{21}&a_{22}&\cdots&a_{2n}\\
               \vdots&\quad&\quad&\vdots\\
               a_{m1}&a_{m2}&\cdots&a_{mn}
\end{pmatrix}
\begin{pmatrix}\color{blue}{x_1}\\\color{blue}{x_2}\\\vdots\\\color{blue}{x_n}\end{pmatrix}=
\color{blue}{x_1}\begin{pmatrix}a_{11}\\a_{21}\\\vdots\\a_{m1}\end{pmatrix}
+\color{blue}{x_2}\begin{pmatrix}a_{12}\\a_{22}\\\vdots\\a_{m2}\end{pmatrix}
+\cdots+\color{blue}{x_n}\begin{pmatrix}a_{1n}\\a_{2n}\\\vdots\\a_{mn}\end{pmatrix}
$$

Define matrix multiplication

$$ A=(a_{ij}) B=(b_{ij}) C=(c_{ij})$$

$$ c_{ij}=\boldsymbol{a}_{i*}\cdot\boldsymbol{b}_{*j},\quad (i=1,\cdots,m;j=1,\cdots,n) $$ 

<div style="width:image width px; 
            font-size:80%; 
            text-align:center; 
            float: middle; padding-left-right-top-bottom:0.5em;  
            border-style: solid; border-color: rgba(211, 211, 211, 0.1);
            background-color: rgba(250, 250, 250);">
    <img style="float: center;" src="image/mm.png">
</div>

In [120]:
m = np.array([[2,3,4],[4,5,6]])
m.shape, m, m[0]

((2, 3),
 array([[2, 3, 4],
        [4, 5, 6]]),
 array([2, 3, 4]))

In [121]:
n = np.array([[4,5,6],[7,8,9]])
n.T.shape, n[0] #n.T[:,0]

((3, 2), array([4, 5, 6]))

In [134]:
# calculate c_11, result of 1st row and 1st col
print ('The result for c11 is',sum([(i*j) for i, j in zip(m[0] ,n.T[:,0])])) # the result is the same as -> sum([(i*j) for i, j in zip(m[0] ,n[0])])
print('the result for c12 is',sum([(i*j) for i, j in zip(m[1],n[0])]))
print ('the result for c21 is',sum([(i*j)for i, j in zip(m[0],n[1])]))
print ('the result for c22 is',sum([(i*j)for i, j in zip(m[1],n[1])]))
# or we can use np.dot
np.dot(m, n.T)

The result for c11 is 47
the result for c12 is 77
the result for c21 is 74
the result for c22 is 122


array([[ 47,  74],
       [ 77, 122]])

# Power of Matrix

if A is a square matrix:
$$ A^1=A,\quad A^2=A^1A^1,\quad\cdots,\quad A^{k+1}=A^kA^1 $$

$$ A^2=AA=\begin{pmatrix}0&0&1\\0&0&0\\0&0&0\end{pmatrix},\quad A^3=A^2A=\begin{pmatrix}0&0&0\\0&0&0\\0&0&0\end{pmatrix} $$ 

# Transpose of a Matrix

$$ (A^\mathrm{T})^\mathrm{T}=A$$
$$(AB)^\mathrm{T}=B^\mathrm{T}A^\mathrm{T}$$
$$(A^\mathrm{T})^n=(A^n)^\mathrm{T}$$
$$(A+B)^\mathrm{T}=A^\mathrm{T}+B^\mathrm{T} $$

In [13]:
A=np.matrix([[1,2],[-2,1]])

In [14]:
(A.dot(A)).T

matrix([[-3, -4],
        [ 4, -3]])

若：
$ A^T=A$

$则矩阵A称为\color{Salmon}{对称矩阵}，对称矩阵一定是方阵。$

若:

$A^T=-A$

$则矩阵A称为\color{Salmon}{反对称矩阵}，反对称矩阵一定是方阵。
比如下面就是对称矩阵：$


$\begin{pmatrix}
1 & 2 & 3\\
2 & 4 & -5\\
3 & -5 & 6\end{pmatrix}^\mathrm{T}
=
\begin{pmatrix}
1 & 2 & 3\\
2 & 4 & -5\\
3 & -5 & 6\end{pmatrix}$

而下面就是反对称矩阵：


$\begin{pmatrix}
0 & 2 & -1 \\
-2 & 0 & -4 \\
1 & 4 & 0\end{pmatrix}^\mathrm{T}
=
-\begin{pmatrix}
0 & 2 & -1 \\
-2 & 0 & -4 \\
1 & 4 & 0\end{pmatrix}$


$定理 矩阵函数A\boldsymbol{x}=\boldsymbol{y}$满足：
齐次性：$A(m\boldsymbol{x})=m(A\boldsymbol{x})$
可加性：$A(\boldsymbol{x}+\boldsymbol{y})=A(\boldsymbol{x})+A(\boldsymbol{y})$
所以矩阵函数是线性函数。

$矩阵函数A\boldsymbol{x}=\boldsymbol{y}，它的输入、输出都是列向量，所以也称为\color{Salmon}{列向量矩阵函数}。当然输入、输出也可以为行向量。$

 行向量矩阵函数
$ 对于m\times n的矩阵A，根据矩阵乘法合法性，$有：

$\underbrace{\boldsymbol{x}^\mathrm{T}}_{1\times m}\quad\underbrace{A}_{m\times n}\quad=\quad\underbrace{\boldsymbol{y}^\mathrm{T}}_{1\times n}$


$ \begin{pmatrix}x_1&x_2&\cdots&x_m\end{pmatrix}\begin{pmatrix}a_{11}&a_{12}&\cdots&a_{1n}\\
a_{21}&a_{22}&\cdots&a_{2n}\\\vdots&\quad&\quad&\vdots\\
a_{m1}&a_{m2}&\cdots&a_{mn}\end{pmatrix}
=
\begin{pmatrix}y_1&y_2&\cdots&y_n\end{pmatrix}$

$这其实也是矩阵函数，只是输入、输出为行向量，也称为\color{Salmon}{行向量矩阵函数}$

向量的数学定义时解释过，行向量、列向量其实是没有区别的，是同一个向量$\boldsymbol{v}的不同代数形式：$

$\boldsymbol{v}=\begin{pmatrix}a_1\\a_2\\\vdots\\a_n\end{pmatrix}=(a_1,a_2,...,a_n)$

$同理，列向量矩阵函数A\boldsymbol{x}=\boldsymbol{y}和它对应的行向量矩阵函数\boldsymbol{x}^\mathrm{T}A^\mathrm{T}=\boldsymbol{y}^\mathrm{T}也是没有区别的，表示的是同一个线性函数，区别只在于输入、输出用的是列向量还是行向量。$