In [1]:
import numpy as np
import math

In [3]:
A = np.matrix([[1,-1],[0,1]])

In [5]:
np.linalg.inv(A)

matrix([[1., 1.],
        [0., 1.]])

In [4]:
x = np.matrix([[0.5,0.5],[-0.5,0.5]])

In [5]:
np.linalg.inv(x)

matrix([[ 1., -1.],
        [ 1.,  1.]])

In [10]:
m = np.matrix([1,1]).T

In [11]:
m

matrix([[1],
        [1]])

In [12]:
e = np.matrix([[1,0],[-1,1]])

In [17]:
np.linalg.inv(e)*m

matrix([[1.],
        [2.]])