$P\boldsymbol{x_{e'}}=\boldsymbol{x_e}\qquad P^{-1}\boldsymbol{x_{e}}=\boldsymbol{x_{e'}}$

P就是过渡矩阵

$P的构成很简单，只需知道\boldsymbol{e_1'},\boldsymbol{e_2'}在\boldsymbol{e_1},\boldsymbol{e_2}下的坐标，并用此坐标作为列向量就可以构造出过渡矩阵：$

$P=(\boldsymbol{e_1'},\boldsymbol{e_2'})$

$Q^{-1}P\boldsymbol{x_{e'}}=\boldsymbol{x_{e''}}$

# 不同基下的同一个映射
<img src="image/diff1.png">
<img src="image/diff2.png">
<img src="image/diff3.png">
<img src="image/diff4.png">
<img src="image/diff5.png">
多解释一句，可能有同学会觉得：

$B=QAP^{-1}$

但是上述图示实际上代表了一个复合函数：

$P^{-1}(A(Q(\boldsymbol{x}_{e'})))=\boldsymbol{y}_{e''}$

因此是：

$B=P^{-1}AQ$

# 2 矩阵等价

因为：

B=PAQ

所以，A和PAQ实际上表示的是同一个线性映射：
<img src="image/diff6.png">

数学上称这两者为等价矩阵，记作：

$A\sim PAQ$



A,B为同型矩阵，A,B等价的充要条件为：

$A\sim B\iff rank(A)=rank(B)$

# 相似矩阵

$如果是\boldsymbol{e_1'},\boldsymbol{e_2'}基往\boldsymbol{e_1'},\boldsymbol{e_2'}基的映射，那么怎么求B：$
<img src="image/diff7.png">
<img src="image/diff8.png">
<img src="image/diff9.png">

因此：

$B=P^{-1}AP$

此时，A和B是特殊的等价矩阵，数学上称这两者为相似矩阵：

设A,B都是n阶矩阵，若有可逆矩阵P，使：

$P^{-1}AP=B$

则称P为相似变换矩阵，称B是A的相似矩阵，记作：

$A\simeq B$

显然，相似矩阵必然也是等价矩阵。

In [26]:
import numpy as np

之前我们说过，用于基变换的过渡矩阵是满秩矩阵，所以等价矩阵的定义如下：

$假设有两个\displaystyle m\times n的矩阵，记作A和B。当且仅当存在两个可逆的方块矩阵： \displaystyle m\times m的矩阵P以及\displaystyle n\times n的矩阵Q，使得：$
B=PAQ
此时，两者等价，记作：
$A\sim B$

In [3]:
m_e1 = [1,1]

In [23]:
A = np.matrix([[np.sqrt(2)/2,-np.sqrt(2)/2],[np.sqrt(2)/2,np.sqrt(2)/
                                             2]])
M_a = [1,1]
m_e = A.dot(M_a)
m_e

matrix([[0.        , 1.41421356]])

In [25]:
B = np.matrix([[2,0],[0,1]])
n_b = [1,1]
n_e = B.dot(n_b)
n_e

matrix([[2, 1]])

In [20]:
q_inv.dot(x_e.T)

matrix([[7.],
        [3.]])

In [24]:
q_inv = np.linalg.inv(q)
q_inv

matrix([[1., 2.],
        [0., 1.]])

In [25]:
matrix_trans = q_inv*p

In [26]:
matrix_trans

matrix([[5., 2.],
        [2., 1.]])

In [27]:
matrix_trans.dot(m)

matrix([[7., 3.]])

In [30]:
P = np.matrix([[1,-1],[1,1]])

In [47]:
P.dot([1,1])

matrix([[0, 2]])

In [49]:
eigein = np.matrix([[1,0],[0,1]])

matrix([[0, 1]])

In [69]:
a = eigein[0,:]-eigein[1,:]
a.T

matrix([[ 1],
        [-1]])

In [70]:
b = eigein[0,:]+eigein[1,:]
b.T

matrix([[1],
        [1]])

In [72]:
P = np.matrix([[1,1],[-1,1]])

In [73]:
P_inv = np.linalg.inv(P)

In [74]:
P_inv.dot([1,1])

matrix([[0., 1.]])

In [87]:
P = np.matrix([[2,-1],[1,3]])
Q = np.matrix([[1,0],[1,2]])
Q_inv = np.linalg.inv(Q)
P

matrix([[ 2, -1],
        [ 1,  3]])

In [88]:
Q

matrix([[1, 0],
        [1, 2]])

In [82]:
matrix_transform = Q_inv*P

In [83]:
matrix_trans

matrix([[5., 2.],
        [2., 1.]])

In [86]:
matrix_transform.dot([2,1])

matrix([[3., 1.]])

In [90]:
np.matrix([[1,0],[0,1]])

matrix([[1, 0],
        [0, 1]])

$A\boldsymbol{x}=\lambda\boldsymbol{x}\implies (A-\lambda I)\boldsymbol{x}=0$

$对于这个齐次方程组，有非零解（特征向量不能是零向量）的条件是：$

$|A-\lambda I|=0$

即：


$f(\lambda)=
\begin{vmatrix}
    a_{11}-\lambda&a_{12}&\cdots&a_{1n}\\
    a_{21}&a_{22}-\lambda&\cdots&a_{2n}\\
    \vdots&\vdots&\quad&\vdots\\
    a_{n1}&a_{n2}&\cdots&a_{nn}-\lambda
\end{vmatrix}=0$

$f(\lambda)是一元n次多项式，称为矩阵A的特征多项式。$

一元n次方程在复数范围内正好有n个复数根。

而下面是特征方程，特征方程是一个一元n次方程：

$f(\lambda)=0$

n个复数根就是n阶矩阵的n个特征值。
$设\lambda=\lambda_i为矩阵A的一个特征值，代入方程：$

$(A-\lambda_i I)\boldsymbol{x}=0\implies \boldsymbol{x}=\boldsymbol{p}_i,\boldsymbol{p}_i\ne \boldsymbol{0}$

$其中，\boldsymbol{p}_i便是对应\lambda_i的特征向量。$



$求解矩阵A=\begin{pmatrix}3&-1\\-1&3\end{pmatrix}的特征值和特征向量。$

In [93]:
A = np.matrix([[3,-1],[-1,3]])
A

matrix([[ 3, -1],
        [-1,  3]])

In [99]:
lam1, lam2 = np.linalg.eigvals(A)

In [100]:
lam1, lam2

(4.0, 2.0)

In [102]:
A_1 = np.matrix([[-1,1,0],[-4,3,0],[1,0,2]])

In [103]:
A_1

matrix([[-1,  1,  0],
        [-4,  3,  0],
        [ 1,  0,  2]])

In [106]:
lam1, lam2, lam3 =np.linalg.eigvals(A_1)

In [111]:
lam1_m = lam1*np.matrix([[1,0,0],[0,1,0],[0,0,1]])

In [113]:
trans_m = A_1-lam1_m

In [116]:
trans_m*np.matrix([0,0,1]).T

matrix([[0.],
        [0.],
        [0.]])

在线性代数中，一个n\times n的矩阵A的迹（或迹数），是指A的主对角线（从左上方至右下方的对角线）上各个元素的总和，一般记作tr(A)：设有矩阵：

$\mathbf{A} = \begin{pmatrix} 3 & 5 & 1\\0 & 9 & 2\\7 & 6 & 4 \end{pmatrix}$



它的迹是：
 $tr(A)= tr\begin{pmatrix} 3 & 5 & 1\\0 & 9 & 2\\7 & 6 & 4 \end{pmatrix} = 3 + 9 + 4 = 16$
 
$假设有n\times n的矩阵：$

$A=(a_{ij})$

并且：

$A的特征值=\{\lambda_{1},\lambda_{2},\cdots,\lambda_{n}\}$

对角线之和等于特征值之和：


$\begin{aligned}
    a_{11}+a_{22}+\cdots+a_{nn}=\lambda_{1}+\lambda_{2}+\cdots+\lambda_{n}\\
\end{aligned}$

即矩阵的迹是其特征值的总和。

array([ 1.        ,  2.41421356, -0.41421356])

In [121]:
m=np.matrix([[1,2,1],[0,1,0],[2,3,1]])

In [122]:
np.linalg.eigvals(m)

array([ 2.41421356, -0.41421356,  1.        ])

In [124]:
mm=np.matrix([[1,1],[4,1]])

In [126]:
v1, v2 = np.linalg.eigvals(mm)

In [128]:
v1, v2

(3.0000000000000004, -0.9999999999999996)

In [138]:
lamda = np.matrix([[3,0],[0,3]])

In [143]:
(mm-lamda).dot([1,2])

matrix([[0, 0]])