把含有n个变量的二次齐次函数：

\begin{aligned}
    f(x_1,x_2,\cdots,x_n)
        &=a_{11}x_1^2+a_{22}x_2^2+\cdots+a_{nn}x_n^2\\
        &+2a_{12}x_1x_2+2a_{13}x_1x_3+\cdots+2a_{n-1,n}x_{n-1}x_n
\end{aligned}
或者二次齐次方程称为二次型。
<img src="image/change of basis.png">
<img src="image/e2.png">
<img src="image/e3.png">
<img src="image/e4.png">

圆的二次型矩阵是这样的：
<img src="image/e9.png">
改变一下二次型矩阵：
<img src="image/e10.png">
哈，原来椭圆和圆之间是线性关系呐（通过矩阵变换就可以从圆变为椭圆）。

继续
<img src="image/e11.png">
咦，双曲线和圆之间也是线性关系。

其实圆、椭圆、双曲线之间关系很紧密的，统称为圆锥曲线，都是圆锥体和平面的交线

<img src="image/e12.png">

从上面动图可看出，一个平面在圆锥体上运动，可以得到圆、椭圆、双曲线，这也是它们之间具有线性关系的来源。

看着不是线性关系的，或许只是因为维度不够高。

对称矩阵的一个应用--二次型

任给一个二次型就能唯一的确定一个对称矩阵，反之，任给一个对称矩阵，也可唯一的确定一个二次型。因此，我们把对称矩阵A叫做二次型f的矩阵。对称矩阵A的秩就叫做二次型的秩。

性质一

可对角化，且特征值为实数

性质二

$设\lambda_1,\lambda_2是对称矩阵A的两个特征值，\boldsymbol{p_1},\boldsymbol{p_2}是对应的特征向量。若\lambda_1\neq \lambda_2,则\boldsymbol{p_1}与\boldsymbol{p_2}正交。$

如果二次型只有二次项：

$k_1x_1^2+k_2x_2^2+\cdots+k_nx_n^2$

则称为二次型的标准型。

如果标准型的系数只在1,-1,0三个数中取值，也就是上式变为：

$y_1^2+\cdots+y_p^2-y_{p+1}^2-\cdots-y_r^2$

任给二次型f，总有正交变换$\boldsymbol{x}=P\boldsymbol{y}，使f化为标准型：$

$f=\lambda_1y_1^2+\cdots+\lambda_ny_n^2$

$其中\lambda_1,\cdots,\lambda_n是f的矩阵A的特征值。$

则上式为二次型的规范型。

标准型对应的矩阵就是：


$\Lambda=
\begin{pmatrix}
    k_1&0&\cdots&0\\
    0&k_2&\cdots&0\\
    \vdots&\vdots&\quad&\vdots\\
    0&0&\cdots&k_n
\end{pmatrix}$

规范型的话，也是对角阵，只是在对角线上只有1,-1,0。

如果，通过“某种方法”，让：

普通二次型\xrightarrow{\quad 某种方法 \quad}标准型

这样做的结果从几何上看，有可能不会发生形变，只是好像从“歪”的变“正”的：
<img src="image/e20.png">
有时候可能会发生形变，但是二次曲线（面）的类型不会改变（下面从椭圆变成圆，本来圆就是椭圆的特例）：
<img src="image/e13.png">

上文提到的“某种方法”，数学上称为“标准化”：

普通二次型\xrightarrow{\quad 标准化 \quad}标准型

从代数上讲，就是有某对称矩阵A，通过标准化：

\boldsymbol{x}^\mathrm{T}A\boldsymbol{x}\xrightarrow{\quad 标准化 \quad}
\boldsymbol{y}^\mathrm{T}\Lambda\boldsymbol{y}

标准化的方法
通过合同矩阵，对二次型进行基变换：

$普通二次型\xrightarrow{\quad 找到合适的基 \quad}标准型$

所谓的合适的基，不止一个，所以标准型并不唯一。

下节课将介绍两种标准化的方法：

正交标准化
配方法化标准型

二次型

$f=2 x_{1}^{2}+3 x_{2}^{2}+3 x_{3}^{2}+4 x_{2} x_{3}$

的标准型为

根据二次型，f的二次型矩阵为：

$A=\begin{pmatrix}2&0&0\\0&3&2\\0&2&3\end{pmatrix}$

$根据特征值特征向量求解，即求|A-\lambda E|=0的根：$

$|\lambda E-A|=\begin{vmatrix}\lambda-2&0&0\\0&\lambda-3&-2\\0&-2&\lambda-3\end{vmatrix}=(\lambda-1)(\lambda-2)(\lambda-5)$

$所以特征值为\lambda_{1}=1, \lambda_{2}=2,\lambda_{3}=5$

再依据二次型的标准型可知，标准型即特征值为系数，因此f的标准型为

$y_1^2+2y_2^2+5y_3^2$

In [8]:
import numpy as np
n = np.matrix([[0,-1,1],[-1,0,1],[1,1,0]])
n

matrix([[ 0, -1,  1],
        [-1,  0,  1],
        [ 1,  1,  0]])

In [9]:
np.linalg.eigvals(n)

array([ 1., -2.,  1.])

In [11]:
np.linalg.eigvals(np.matrix([[1,-4],[-4,-5]]))

array([ 3., -7.])

In [15]:
lamda1, lamda2 = np.linalg.eigvals(np.matrix([[57.2,45.2],[45.2, 36.7]]))

In [45]:
a = np.matrix([[2,0,0],[0,3,2],[0,2,3]])

In [46]:
a

matrix([[2, 0, 0],
        [0, 3, 2],
        [0, 2, 3]])

In [58]:
lamada1, lamada2, lamada3 = np.linalg.eigvals(a)
lamada1,lamada2,lamada3

(5.0, 1.0000000000000004, 2.0)

性质一

可对角化，且特征值为实数

性质二

$设\lambda_1,\lambda_2是对称矩阵A的两个特征值，\boldsymbol{p_1},\boldsymbol{p_2}是对应的特征向量。若\lambda_1\neq \lambda_2,则\boldsymbol{p_1}与\boldsymbol{p_2}正交。$

对称矩阵A为正定的充分必要条件是：A的特征值为正。

In [126]:
a,b,c = np.linalg.eigvals(np.matrix([[-2,1,1],[0,2,0],[-4,1,3]])
                         )
a,b,c

(-1.0, 2.0, 2.0)

In [127]:
eigen = np.matrix([[1,0,0],[0,1,0],[0,0,1]])

In [131]:
trans1 = np.matrix([[-2,1,1],[0,2,0],[-4,1,3]])-b*eigen

In [133]:
trans1.dot([1,4,0])

matrix([[0., 0., 0.]])

In [99]:
trans2 = np.matrix([[2,2,-2],[2,5,-4],[-2,-4,5]])-b*eigen

In [105]:
trans3.dot([1,2,2])

matrix([[ 0.0000000e+00,  0.0000000e+00, -4.4408921e-16]])

In [104]:
trans3 = np.matrix([2,-2,0],[-2,1,-2],[0,-2,0])-c*eigen

In [114]:
a,b,c

(0.9999999999999991, 9.999999999999996, 0.9999999999999999)

In [135]:
import scipy.linalg as sl

In [147]:
a = np.array([[np.sqrt(2)/2,1,0],[np.sqrt(2)/2,0,0],[0,0,1]])

In [151]:
a = np.matrix([[np.sqrt(2)/2,1,0],[np.sqrt(2)/2,0,0],[0,0,1]])

In [152]:
sl.orth(a.T)

array([[-0.70710678,  0.        , -0.70710678],
       [-0.70710678,  0.        ,  0.70710678],
       [ 0.        ,  1.        ,  0.        ]])

In [145]:
from sympy import *

In [153]:
GramSchmidt(a.T,True)

AttributeError: 'matrix' object has no attribute 'is_zero_matrix'