In [1]:
import numpy as np

In [2]:
my_list = [42,14,19]

In [7]:
arr = np.array(my_list, dtype = 'int8')

In [8]:
arr

array([42, 14, 19], dtype=int8)

In [9]:
arr.dtype

dtype('int8')

In [10]:
import pandas as pd

In [12]:
df = pd.DataFrame({'cost':[1,2,3,4,5],'to_pay':[20,12,3,56,7]})

In [14]:
df['to_pay'].values

array([20, 12,  3, 56,  7])

In [16]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones(((5,2)))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
arr_2=np.full((2,10),42)

In [20]:
arr_2.shape

(2, 10)

In [23]:
np.arange(4,20,2)

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
np.linspace(2,4,43) # 43 numbers between 2 and 4. 

array([2.        , 2.04761905, 2.0952381 , 2.14285714, 2.19047619,
       2.23809524, 2.28571429, 2.33333333, 2.38095238, 2.42857143,
       2.47619048, 2.52380952, 2.57142857, 2.61904762, 2.66666667,
       2.71428571, 2.76190476, 2.80952381, 2.85714286, 2.9047619 ,
       2.95238095, 3.        , 3.04761905, 3.0952381 , 3.14285714,
       3.19047619, 3.23809524, 3.28571429, 3.33333333, 3.38095238,
       3.42857143, 3.47619048, 3.52380952, 3.57142857, 3.61904762,
       3.66666667, 3.71428571, 3.76190476, 3.80952381, 3.85714286,
       3.9047619 , 3.95238095, 4.        ])

In [33]:
np.random.rand(1)# random number bweet 0 and 1

array([0.37754449])

In [34]:
np.random.rand(2,5) # (2,5) is the shape

array([[0.67157363, 0.89472914, 0.27274504, 0.09572367, 0.08105458],
       [0.21610473, 0.51597186, 0.97420754, 0.35647921, 0.08417506]])

In [35]:
arr1 = np.arange(5)

In [42]:
arr1.shape

(5,)

In [38]:
arr2 = np.ones((1,5))

In [43]:
arr2.shape

(1, 5)

In [40]:
arr1 + arr2

array([[1., 2., 3., 4., 5.]])

In [44]:
arr1 > arr2

array([[False, False,  True,  True,  True]])

In [49]:
import random
random.choices(population=[['a','b'], ['b','a'], ['c','b']],weights=[0.2, 0.2, 0.6],k=10)

[['a', 'b'],
 ['c', 'b'],
 ['a', 'b'],
 ['c', 'b'],
 ['b', 'a'],
 ['c', 'b'],
 ['c', 'b'],
 ['c', 'b'],
 ['a', 'b'],
 ['b', 'a']]